### ISSUE TITLE
Publish Library to CDN and consume with angular 2 webpack?

### ISSUE THREAD

**Issue by shaikhspear16** [jhades/angular2-library-example#8]
Following the steps (http://blog.angular-university.io/how-to-create-an-angular-2-library-and-how-to-consume-it-jspm-vs-webpack/) I have created the library.
|____components.d.ts
    |____components.js
    |____lib
    | |____HelloWorld.d.ts
    | |____HelloWorld.js
    | |____HelloWorld.js.map
    |____package.json

I want to share the library with multiple projects and do not want it published with npm. So I have hosted the library at an internal CDN., such as - "http://my-local-cdn-website/cdn/dist/a2-libraries/component"

How do I consume the library in other projects having angular 2 with webpack.

**Comment by jkeczan** [comment]
We share libraries internally quite a bit at my work. What we do though is host a private NPM repository behind our firewall and configure our applications to use it instead.

We set it up to passthrough for any library it doesn't have. 

You can do this using some libraries out there like [Sinopia](https://github.com/rlidwka/sinopia)

Setup can be a little tricky but once you get the hang of it, works like magic

UPDATE:
It looks like repository for Sinopia is abandoned. A more active fork is [here](https://www.npmjs.com/package/verdaccio)

**Comment by shaikhspear16** [comment]
I did this by using webpack's DLLPlugin and DLLReferencePlugin.
Closing this!
